workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60

    environment:
      node: 20

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web
        script: npm run build

      - name: Capacitor sync (Android)
        script: npx cap sync android

      - name: Build Android debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

  ios-release:
    name: iOS Release (IPA)
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest
      vars:
        APP_BUNDLE_ID: "com.damsstudio.hermoodmap"
        APP_TEAM_ID: "KX8Z996CGK"

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web
        script: npm run build

      - name: Capacitor add + sync (iOS)
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: Install signing assets from Codemagic (P12 + profiles)
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Resolve installed provisioning profile UUID
        script: |
          set -e

          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "Listing provisioning profiles in: $PROFILES_DIR"
          ls -la "$PROFILES_DIR" || true

          UUID=""
          for f in "$PROFILES_DIR"/*.mobileprovision; do
            [ -f "$f" ] || continue
            # Decode the mobileprovision (it’s a CMS blob) and grep for the bundle id
            if security cms -D -i "$f" | /usr/bin/plutil -convert json -o - - | grep -q "\"application-identifier\".*$APP_TEAM_ID\.$APP_BUNDLE_ID"; then
              UUID="$(basename "$f" .mobileprovision)"
              echo "Matched profile file: $f"
              echo "Resolved PROVISIONING_PROFILE_SPECIFIER UUID: $UUID"
              break
            fi
          done

          if [ -z "$UUID" ]; then
            echo "ERROR: Could not find an installed provisioning profile matching $APP_TEAM_ID.$APP_BUNDLE_ID"
            echo "Dumping decoded profile summaries for debugging:"
            for f in "$PROFILES_DIR"/*.mobileprovision; do
              [ -f "$f" ] || continue
              echo "---- $f ----"
              security cms -D -i "$f" | /usr/bin/plutil -p - | head -n 80 || true
            done
            exit 1
          fi

          echo "PROVISIONING_PROFILE_UUID=$UUID" >> "$CM_ENV"

      - name: Build iOS archive + export IPA
        script: |
          set -e
          cd ios/App

          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            DEVELOPMENT_TEAM="$APP_TEAM_ID" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_UUID" \
            clean archive

          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/build/ipa"

    artifacts:
      - build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
