workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60

    environment:
      node: 20

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web
        script: npm run build

      - name: Capacitor sync (Android)
        script: npx cap sync android

      - name: Build Android debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

  ios-release:
    name: iOS Release (IPA)
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest
      vars:
        APP_BUNDLE_ID: "com.damsstudio.hermoodmap"
        APP_TEAM_ID: "KX8Z996CGK"
        APP_STORE_PROFILE_NAME: "HerMoodMap_AppStore"

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web
        script: npm run build

      - name: Capacitor add + sync (iOS)
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: Install signing assets from Codemagic (P12 + profiles)
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Build iOS archive + export IPA
        script: |
          set -e
          cd ios/App

          # Force archive signing to use the uploaded App Store profile (not Development)
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            DEVELOPMENT_TEAM="$APP_TEAM_ID" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$APP_STORE_PROFILE_NAME" \
            clean archive

          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/build/ipa"

    artifacts:
      - build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
