workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60

    environment:
      node: 20

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web
        script: npm run build

      - name: Capacitor sync (Android)
        script: npx cap sync android

      - name: Build Android debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

  ios-release:
    name: iOS Release (IPA)
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web
        script: npm run build

      - name: Capacitor add + sync (iOS)
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: Build iOS archive + export IPA
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos -archivePath $CM_BUILD_DIR/build/App.xcarchive -allowProvisioningUpdates DEVELOPMENT_TEAM=KX8Z996CGK CODE_SIGN_STYLE=Automatic clean archive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/App.xcarchive -exportOptionsPlist $CM_BUILD_DIR/ExportOptions.plist -exportPath $CM_BUILD_DIR/build/ipa

    artifacts:
      - build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
