workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60

    environment:
      node: 20

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web
        script: npm run build

      - name: Capacitor sync (Android)
        script: npx cap sync android

      - name: Build Android debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

  ios-release:
    name: iOS Release (IPA)
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest

      groups:
        - appstore

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.damsstudios.hermoodmap

      vars:
        APP_TEAM_ID: "KX8Z996CGK"
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"

        PROFILE_REFERENCE: "appstore-profile"
        CERT_REFERENCE: "apple-distribution"

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web
        script: npm run build

      - name: Capacitor add + sync (iOS)
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: Install signing assets into keychain
        script: |
          keychain initialize
          keychain add-certificates

      - name: Apply provisioning profiles to Xcode project
        script: xcode-project use-profiles

      - name: Build IPA for App Store
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
