workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60

    environment:
      node: 20

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web
        script: npm run build

      - name: Capacitor sync (Android)
        script: npx cap sync android

      - name: Build Android debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk


  ios-release:
    name: iOS Release (IPA)
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest

      # 🔴 HARD-WIRED (no UI, no groups)
      vars:
        # App Store Connect API
        APP_STORE_CONNECT_ISSUER_ID: "PASTE_ISSUER_ID_HERE"
        APP_STORE_CONNECT_KEY_ID: "PASTE_KEY_ID_HERE"
        APP_STORE_CONNECT_PRIVATE_KEY: |
          -----BEGIN PRIVATE KEY-----
          PASTE_FULL_P8_CONTENT_HERE
          -----END PRIVATE KEY-----

        # Signing
        CM_IOS_PROVISIONING_PROFILE_SPECIFIER: "HerMoodMap_AppStore"

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web
        script: npm run build

      - name: Capacitor add + sync (iOS)
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: Install signing assets
        script: |
          keychain initialize

          app-store-connect fetch-signing-files com.damsstudio.hermoodmap \
            --type IOS_APP_STORE \
            --create

      - name: Build iOS archive + export IPA
        script: |
          set -e
          cd ios/App

          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            DEVELOPMENT_TEAM=KX8Z996CGK \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="HerMoodMap_AppStore" \
            CODE_SIGNING_ALLOWED=NO \
            clean archive

          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/build/ipa"

    artifacts:
      - build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
